services:
  postgres:
    image: postgres:17
    container_name: tripzy_postgres

    environment:
      POSTGRES_USER: tripzy
      POSTGRES_PASSWORD: tripzypassword
      POSTGRES_DB: tripzy_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: